name: CI/CD para Proyecto Java

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado a la última versión

      # Paso 2: Configurar JDK
      - name: Configurar JDK
        uses: actions/setup-java@v4 # Actualizado a la última versión
        with:
          distribution: 'adopt'
          java-version: '11'

      # Paso 3: Construir el proyecto
      - name: Construcción con Maven
        run: mvn clean install

      # Paso 4: Ejecutar pruebas
      - name: Ejecutar pruebas
        run: mvn test

      # Paso 5: Análisis estático con Checkstyle
      - name: Checkstyle
        run: mvn checkstyle:check
        continue-on-error: true

      # Paso 6: Análisis estático con SpotBugs
      - name: SpotBugs
        run: mvn spotbugs:spotbugs

      - name: Subir reporte SpotBugs
        uses: actions/upload-artifact@v3
        with:
          name: reporte-spotbugs
          path: target/spotbugs-html

      # Paso 7: Generar Reporte de Cobertura con JaCoCo
      - name: Generar Reporte de Cobertura
        run: mvn jacoco:report

      # Paso 8: Subir reporte de cobertura como artefacto
      - name: Guardar Reporte de Cobertura
        uses: actions/upload-artifact@v3
        with:
          name: reporte-cobertura
          path: target/site/jacoco/index.html
